name: Devindocs
on:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo hello,world
        
  
  deploy-dev:
      runs-on: ubuntu-latest
      environment:
        name: Desenvolvimento
        url: 'https://www.uol.com.br'
      needs: build
      steps:
        - name: Run a one-line script
          run: echo deploy Desenvolvimento
  
  
  deploy-homologacao:
      runs-on: ubuntu-latest
      environment:
        name: Homolog
        url: 'https://www.uol.com.br'
      needs: deploy-dev
      steps:
        - name: Run a one-line script
          run: echo deploy Homologaçao
  
  deploy-producao:
      runs-on: ubuntu-latest
      environment:
        name: Produção
        url: 'https://www.uol.com.br'
      needs: deploy-homologacao
      steps:
        - name: Run a one-line script
          run: echo deploy Produção
  
